package com.yuroyami.syncplay.player

import android.annotation.SuppressLint
import android.content.Context
import android.content.res.AssetManager
import android.database.Cursor
import android.net.Uri
import android.os.ParcelFileDescriptor
import android.provider.OpenableColumns
import android.util.Log
import androidx.lifecycle.lifecycleScope
import androidx.media3.common.C
import androidx.media3.common.MediaItem
import androidx.media3.common.MimeTypes
import androidx.media3.common.PlaybackException
import androidx.media3.common.Player
import androidx.media3.common.TrackSelectionOverride
import androidx.media3.common.Tracks
import androidx.media3.exoplayer.DefaultLoadControl
import androidx.media3.exoplayer.DefaultRenderersFactory
import androidx.media3.exoplayer.ExoPlayer
import androidx.media3.exoplayer.trackselection.DefaultTrackSelector
import androidx.media3.session.MediaSession
import androidx.media3.ui.AspectRatioFrameLayout
import androidx.media3.ui.PlayerView
import app.R
import app.activities.WatchActivity
import app.playback.PlaybackProperties
import com.yuroyami.syncplay.player.HighLevelPlayer.ENGINE.EXOPLAYER
import com.yuroyami.syncplay.player.HighLevelPlayer.ENGINE.MPV
import com.yuroyami.syncplay.player.HighLevelPlayer.ENGINE.VLC
import app.player.mpv.MPVView
import app.protocol.JsonSender
import com.yuroyami.syncplaymobile.utils.MiscUtils.getFileName
import com.yuroyami.syncplaymobile.utils.MiscUtils.string
import com.yuroyami.syncplaymobile.utils.MiscUtils.toasty
import com.yuroyami.syncplaymobile.utils.RoomUtils.sendPlayback
import com.yuroyami.syncplaymobile.wrappers.MediaFile
import com.yuroyami.syncplaymobile.wrappers.Track
import com.google.common.util.concurrent.Futures
import com.google.common.util.concurrent.ListenableFuture
import `is`.xyz.mpv.MPVLib
import `is`.xyz.mpv.MPVLib.mpvFormat.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.util.Collections
import kotlin.math.abs


